spring.application.name=whatjavaBoladao

# 1. Database Connection (Change 'db_name' to your real database name)
spring.datasource.url=jdbc:postgresql://localhost:5432/whatsapp
spring.datasource.username=postgres
spring.datasource.password=senha123

# 2. Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. Port (optional, but good to keep 8080)
server.port=8080

#jwt tokens
jwt.secret=my-super-long-and-secure-secret-key-that-is-at-least-32-chars
jwt.expiration=3600000